config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get 'profile-page', to: 'pages#profile_page'

  resources :personalized_trainers do
    resources :bookings, only: [:create, :edit, :update, :destroy, :show]
  end

  get 'dashboard', to: 'dashboards#index'

  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/personalized_trainer.rb
class PersonalizedTrainer < ApplicationRecord

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one :review, through: :booking

  validates :name, presence: true
  validates :category, presence: true
  validates_length_of :description, minimum: 6
  validates :location, presence: true
  validates :rate, presence: true

  include PgSearch::Model
  pg_search_scope :search_by,
                  against: {
                    category: 'A',
                    location: 'B',
                    name: 'C'
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/controllers/personalized_trainers_controller.rb
class PersonalizedTrainersController < ApplicationController
  before_action :set_personalized_trainer, only: [:show, :edit, :destroy, :update]

  def index
    if params[:query].present?
      @personalized_trainers = PersonalizedTrainer.search_by(params[:query])
    elsif params[:category]
      @personalized_trainers = PersonalizedTrainer.where(category: params[:category])
    else
      @personalized_trainers = PersonalizedTrainer.all
    end

    @markers = @personalized_trainers.geocoded.map do |personalized_trainer|
      {
        lat: personalized_trainer.latitude,
        lng: personalized_trainer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { personalized_trainer: personalized_trainer })
      }
    end
  end

  def show
    @booking = Booking.new
    @bookings = @personalized_trainer.bookings
  end

  def new
    @personalized_trainer = PersonalizedTrainer.new
  end

  def create
    @personalized_trainer = PersonalizedTrainer.new(personalized_trainer_params)
    @personalized_trainer.user = current_user
    if @personalized_trainer.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    set_personalized_trainer
    if @personalized_trainer.update(personalized_trainer_params)
      redirect_to @personalized_trainer
    else
      render :edit
    end
  end

  private

  def set_personalized_trainer
    @personalized_trainer = PersonalizedTrainer.find(params[:id])
  end

  def personalized_trainer_params
    params.require(:personalized_trainer).permit(:name, :category, :description, :location, :rate, :photo, :user_id, :education)
  end
end

app/views/personalized_trainers/_info_window.html.erb
<div class="card shadow" style="width: 50;">
  <div>
    <% if personalized_trainer.photo.attached? %>
      <%= cl_image_tag personalized_trainer.photo.key, :gravity=>"face", :height=>100, :width=>100, :zoom=>0.7, :crop=>"thumb"%>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= personalized_trainer.name %></h5>
    <p class="card-text"><%= personalized_trainer.category %></p>
    <p class="card-text"><%= personalized_trainer.location %></p>
    <p class="card-text"> <%= link_to "See more", personalized_trainer_path(personalized_trainer.id) %></p>
  </div>
</div>

app/views/personalized_trainers/edit.html.erb
<div class="container">
  <div class="row justify-content-center p-3">
    <div class="col-md-6 m-2 p-4 form-card-shadow">

    <div class= "row justify-content-center">
      <div class="col-md-3">
        <% if @personalized_trainer.photo.attached? %>
            <td> <%= cl_image_tag @personalized_trainer.photo.key, :gravity=>"face", :height=>100, :width=>100, :zoom=>0.7, radius: "max", :crop=>"fill"%> </td>
          <% else %>
            <td> </td>
          <% end %>
      </div>
      <div class="col-md-9">
        <h4>Edit Personal Trainer: </h4>
        <h5><i class="far fa-edit link-theme-yell"></i> <%= @personalized_trainer.name %></h5>
      </div>
    </div>

        <%= simple_form_for(@personalized_trainer) do |f| %>
        <%= f.input :name %>
        <%= f.input :category, placeholder: 'eg. crossfit' %>
        <%= f.input :education, placeholder: 'eg. university/diploma' %>
        <%= f.input :description, placeholder: 'eg. tell us about your trainer' %>
        <%= f.input :location, placeholder: 'eg. city' %>
        <%= f.input :rate, placeholder: 'per day' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: "btn-theme" %>
        <% end %>

    </div>
  </div>
</div>

app/views/personalized_trainers/index.html.erb
<div class="container">

  <div class="row justify-content-center m-auto">
    <div class="col-md-8 mt-4 mb-2">
      <%= form_tag personalized_trainers_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control py-2 rounded-pill mr-1 pr-5",
        placeholder: "Find a PT in your area.." %>
    </div>

    <div class="col-md-2 mt-4 mb-2">
      <%= submit_tag "Search", class: "btn rounded-pill border" %>
      <% end %>
    </div>
  </div>

  <div class="p-2 m-2">
    <h2> Trainers in selected map area <i class="fas fa-globe-africa"></i> </h2>
  </div>

  <div class="row pt-2">

    <div class="col-md-5 mb-2">
      <% @personalized_trainers.each do |personalized_trainer| %>
      <div class="card-product p-3 mb-3 bg-white rounded-card-border">
        <% if personalized_trainer.photo.attached? %>
        <%= cl_image_tag personalized_trainer.photo.key, height: 300 , width: 200, :crop=>"fill", :radius => 20 %>
        <% else %>
        <p> " " </p>
        <% end %>
        <div class="card-product-infos">
          <div class="m-2">
            <h4 class="card-title"><%= link_to personalized_trainer.name, personalized_trainer_path(personalized_trainer.id), class: 'link-remove-black' %></h4>
            <h5> <%= personalized_trainer.category %></h5>
          </div>
          <div class="m-2 bttm-border">
            <p class="card-text"> <i class="fas fa-globe-africa theme-color"></i> <%= personalized_trainer.location %></p>
            <p class="card-text"> <i class="fas fa-university theme-color"></i> <%= personalized_trainer.education %></p>
            <p class="card-text"> <i class="fas fa-euro-sign theme-color"></i> <%= personalized_trainer.rate %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <div class="col-md-7">
      <div class="sticky-top shadow rounded">
        <div class="" id="map"
        style="width: auto; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>


</div>
</div>

app/views/personalized_trainers/new.html.erb
<div class="container">
  <div class="row justify-content-center p-3">
    <div class="col-md-6 m-2 p-4 form-card-shadow">

    <div class= "row justify-content-center">
      <h4> Create a Personal Trainer </h4>
    </div>

        <%= simple_form_for(@personalized_trainer) do |f| %>
        <%= f.input :name %>
        <%= f.input :category, placeholder: 'eg. crossfit' %>
        <%= f.input :education, placeholder: 'eg. university/diploma' %>
        <%= f.input :description, placeholder: 'eg. tell us about your trainer' %>
        <%= f.input :location, placeholder: 'eg. city' %>
        <%= f.input :rate, placeholder: 'per day' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit :Submit, class: "btn-theme" %>
        <% end %>

    </div>
  </div>
</div>

app/views/personalized_trainers/show.html.erb
<div class="container">

  <div class="row mb-3">
    <div class="col-12">
      <h2 class="text-center mt-3"> <%= @personalized_trainer.name %> is a personal trainer in <%= @personalized_trainer.category %> </h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 form-card-shadow m-2 p-3">
      <div class="card-trip row">

        <div class="col-md-5 text-center">
          <% if @personalized_trainer.photo.attached? %>
          <%= cl_image_tag @personalized_trainer.photo.key, height: 300 , width: 200, :gravity=>"faces", :crop=>"fill", :radius => 20 %>
          <% end %>
        </div>

        <div class="card-trip-infos col-md-6 m-3">
          <div class="mb-3">
            <h3 class="font-weight-light"><%= @personalized_trainer.name %></h3>
            <h4 class="grey font-weight-bold"> Category: <%= @personalized_trainer.category %></h4>
          </div>
          <div class="mt-2">
            <p class="fs-paragraph"> <i class="fas fa-globe-africa theme-color"></i> <%= @personalized_trainer.location %></p>
            <p class="fs-paragraph"> <i class="fas fa-university theme-color"></i> <%= @personalized_trainer.education %></p>
            <p class="fs-paragraph"> <i class="fas fa-euro-sign theme-color"></i> <%= @personalized_trainer.rate %></p>
          </div>
        </div>
      </div>
      <div class="mt-3 ml-3">
        <p class="fs-paragraph"> <i class="fas fa-ellipsis-v theme-color"></i> <%= @personalized_trainer.description %></p>
      </div>
    </div>

    <div class="col-md-5 form-card-shadow m-2 p-3">
      <div id='personalized_trainer-booking-dates' data-unavailable="<%= @personalized_trainer.unavailable_dates.to_json %>">
        <h3> Make a booking </h3>
        <div class="dates">
          <div class="form-inputs">
            <div class="form-row fs-paragraph">
              <% if true %>
              <%= simple_form_for([@personalized_trainer, @booking]) do |f| %>
              <%= f.label :start_date, 'Start Date' %>
              <%= f.input :start_date, placeholder: "To", as: :string, type: :text, label: false %>
              <%= f.label :end_date, 'End Date' %>
              <%= f.input :end_date, placeholder: "To", as: :string, type: :text, label: false %>
            </div>
          </div>
        </div>

        <div class="form-inputs fs-paragraph">
          <%= f.input :goal, placeholder: "Give #{@personalized_trainer.name} an idea of your goal!", class: "btn btn-primary btn-lg btn-block btn-booking" %>
          <%= f.submit "Book now", class: "btn-theme btn-block btn-booking", data: { confirm: "Are you sure you want to confirm your booking?" } %>
          <%= link_to "Browse", personalized_trainers_path, class: "btn-theme-cancel btn-block text-center" %>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 form-card-shadow m-3 p-4">
        <h3>Reviews</h3>

        <% if @bookings.empty? %>
        <small><em class="text-muted">Be the first one to review <%= @personalized_trainer.name %> </em></small>
        <% end %>
        <% if @bookings %>
        <% @bookings.each do |booking| %>
        <% booking.review.each do |review| %>
        <div class="border-bottom mt-3">
          <div>
            <% review.rating.times do %>
            <i class="fas fa-star star-yellow theme-color"></i>
            <% end %>
            <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
            <p class="mb-0 fs-paragraph"><%= review.comment %></p>
          </div>
          <small><em class="text-muted"> <%= booking.user.name %> </em></small>
        </div>
        <% end %>
        <% end %>
        <% end %>

      </div>
    </div>

  </div>