config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get 'profile-page', to: 'pages#profile_page'

  resources :personalized_trainers do
    resources :bookings, only: [:create, :edit, :update, :destroy, :show]
  end

  get 'dashboard', to: 'dashboards#index'

  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @personalized_trainers = current_user.personalized_trainers
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    # 3. My bookings with Trainers
    @my_bookings = current_user.bookings
    # @my_bookings = Booking.where(user: current_user)
    # raise

    # 2. My Team
    @personalized_trainers = current_user.personalized_trainers.order(params[:sort])

    # 1. incoming pending requests
    @requests = @personalized_trainers
    # raise

    # COUNTS

    # 4. Count my pending requests
    @pending_requests_count = 0
    @my_bookings.each do |booking|
      @pending_requests_count += 1 if booking.status == "pending"
    end

    @confirmed_requests_count = 0
    @my_bookings.each do |booking|
      @confirmed_requests_count += 1 if booking.status == "accepted"
    end
  end
end

app/views/dashboards/index.html.erb
<div class="container">

  <div class="row mb-3">
    <div class="col-md-6 m-3">
      <h1 class="mb-2"> <i class="fas fa-chart-line"></i> Dashboard </h1>
      <h3 class="link-theme-yell"> Welcome <%= link_to current_user.name, profile_page_path %>! </h3>
    </div>
    <div class="col-md-6">

    </div>
  </div>

  <div class="row mb-3">

    <div class="col-md-5">
      <h3 class="mb-3"> <i class="fab fa-product-hunt"></i> Pending Client Requests </h3>
      <p class="text-theme-yell"> Please confirm client requests: <% if @pending_requests_count %><%= @pending_requests_count %><% end %> </p>
      <table class="table table-striped table-hover table-responsive table-sm table-shadow fs-paragraph">
      <tr class="">
        <th> Personal Trainer </th>
        <th> Start Date </th>
        <th> End Date </th>
        <th> Reservation Status </th>
        <th> Client </th>
      </tr>

      <% if @requests %>
          <% @requests.each do |trainer| %>
            <%trainer.bookings.each do |booking| %>
              <% if booking.status == "pending" %>
                <tr class="">
                  <td><%= trainer.name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td class="text-center btn-group">
                    <% if booking.status == "pending" %>
                      <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, :input_html => { :value => "accepted" } %>
                      <%= button_tag do %>
                        <i class='far fa-check-circle theme-color p-2'></i>
                      <% end %>
                      <% end %>
                      <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, :input_html => { :value => "declined" } %>
                      <%= button_tag do %>
                        <i class='far fa-window-close theme-color p-2'></i>
                      <% end %>
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= booking.user.name %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </table>

      <h3 class="mb-3"> <i class="fab fa-adn"></i> Client Reservations </h3>
      <p class="text-theme-yell"> Confirmed client reservations: <% if @confirmed_requests_count %><%= @confirmed_requests_count %><% end %></p>
      <table class="table table-striped table-hover table-responsive table-sm table-shadow fs-paragraph">
        <tr class="">
          <th> Personal Trainer </th>
          <th> Start Date </th>
          <th> End Date </th>
          <th> Reservation Status </th>
          <th> Client </th>
        </tr>

        <% if @requests %>
          <%@requests.each do |trainer|  %>
            <%trainer.bookings.each do |booking|  %>
              <% if booking.status == "accepted" %>
                <tr class="table-light">
                  <td><%= trainer.name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td><%= booking.status.capitalize %></td>
                  <td><%= booking.user.name %></td>
                </tr>
              <%end %>
            <%end %>
          <%end %>
        <%end %>
      </table>
    </div>

    <div class="col-md-7">
      <h3 class="mb-3"> <i class="fas fa-users"></i> My Team </h3>
      <p class="text-theme-yell"> Edit your team or <%= link_to ' add Personal Trainer', new_personalized_trainer_path, class: 'btn-theme' %> </p>
      <table class="table table-striped table-hover table-responsive table-sm table-shadow fs-paragraph">
        <tr class="">
          <th> </th>
          <th class="link-remove-black"> <%= link_to "Trainer", :sort => "name" %> </th>
          <th class="link-remove-black"> <%= link_to "Category", :sort => "category"%> </th>
          <th class="link-remove-black"> <%= link_to "Location", :sort => "location" %> </th>
          <th> Rate </th>
          <th> </th>
          <th> </th>
        </tr>
        <% @personalized_trainers.each do |personalized_trainer| %>
          <tr class="">
            <% if personalized_trainer.photo.attached? %>
              <td> <%= cl_image_tag personalized_trainer.photo.key, :gravity=>"face", :height=>100, :width=>100, :zoom=>0.7, radius: '', :crop=>"thumb"%> </td>
            <% else %>
                <td> </td>
            <% end %>
            <td> <%= link_to personalized_trainer.name, personalized_trainer_path(personalized_trainer.id), class: 'link-remove-black' %> </td>
            <td> <%= personalized_trainer.category %> </td>
            <td> <%= personalized_trainer.location %> </td>
            <td> <%= personalized_trainer.rate %> </td>
            <td> <%= link_to edit_personalized_trainer_path(personalized_trainer) do %>
              <i class="far fa-edit link-theme-yell"></i>
              <% end %>
            </td>
            <td> <%= link_to personalized_trainer_path(personalized_trainer), method: :delete, data: { confirm: "Delete ?" } do %>
              <i class="fas fa-trash-alt link-theme-yell"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

  </div>

  <div class="row mb-3">
    <div class="col-md-12">
      <h3 class="mb-3"> <i class="fas fa-dumbbell"></i> <%= current_user.name %>'s Training Sessions </h3>
        <p class="text-theme-yell"> These are the sessions that you have booked: </p>
        <table class="table table-sm table-hover table-shadow fs-paragraph">
          <tr class="">
            <th> Personal Trainer </th>
            <th> Start Date </th>
            <th> End Date </th>
            <th> Reservation Status </th>
            <th> Change Reservation </th>
            <th> Total Booking Fee </th>
            <th> My Goal </th>
            <th> Review </th>
            <th> Remove </th>
          </tr>

          <% if @my_bookings %>
            <%@my_bookings.each do |booking|  %>
              <% if booking.status == "accepted" || booking.status == "declined" %>
                <tr class="">
                  <td><%= booking.personalized_trainer.name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td><%= booking.status.capitalize %></td>
                  <td><%= link_to "Edit booking", edit_personalized_trainer_booking_path(booking.personalized_trainer_id, booking) %></td>
                  <td><%= booking.fee %>$</td>
                  <td><%= booking.goal %></td>
                  <td><%=link_to "Leave a review", new_booking_review_path(booking.id) %></td>
                  <td><%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, :input_html => { :value => "completed" } %>
                      <%= button_tag do %>
                      <i class="fas fa-minus-square theme-color p-2"></i>
                      <% end %>
                      <% end %>
                  </td>
                <%end %>
              <%end %>
            <%end %>
        </table>
    </div>
  </div>

  <div class="col-md-12">
    <h3 class="mb-3"> <i class="fas fa-file-invoice"></i> Accounts </h3>
    <div class="p-3">
      <p> <%= link_to "Visit Accounts & Billing" %> </p>
      <p> <%= link_to "Send Invoice" %> </p>
    </div>
  </div>

</div>